export const site = {
  name: "Achat Avis Google",
  domain: "achat-avis-google.com",
  url: "https://achat-avis-google.com",
  tagline: "La plateforme pour collecter de vrais avis clients",
  description:
    "Achat Avis Google aide les entreprises à collecter, gérer et mettre en valeur des avis clients authentiques sur Google, Trustpilot et les autres plateformes. E-réputation conforme et durable.",
  logo: "https://achat-avis-google.com/images/logo.png",
  ogImage: "https://achat-avis-google.com/images/og-default.png",
  author: {
    name: "Équipe Achat Avis Google",
    url: "https://achat-avis-google.com/e-reputation",
  },
  company: {
    legalName: "Achat Avis Google",
    address: {
      street: "23 RUE DES GRANDS AUGUSTINS",
      city: "PARIS",
      region: "Île-de-France",
      postalCode: "75006",
      country: "France",
    },
    phone: "+33 1 84 16 35 29",
    phoneDisplay: "01 84 16 35 29",
    email: "contact@achat-avis-google.com",
    siret: "43010627800293",
    tva: "FR14430106278",
  },
  social: {
    facebook: "https://facebook.com/achatsavis",
    linkedin: "https://linkedin.com/company/achatsavis",
    instagram: "https://instagram.com/achatsavis",
  },
} as const;

export type NavItem = { label: string; href: string };

export const mainNav: NavItem[] = [
  { label: "Accueil", href: "/" },
  { label: "Fonctionnalités", href: "/#fonctionnalites" },
  { label: "Blog", href: "/blog" },
  { label: "Ressources", href: "/ressources" },
  { label: "Tarifs", href: "/tarifs" },
  { label: "Outils", href: "/outils/generateur-avis" },
  { label: "Audit de fiche", href: "/outils/audit-fiche" },
  { label: "E-réputation", href: "/e-reputation" },
  { label: "Contact", href: "/contact" },
];

export const metiers = [
  "Plombier",
  "Électricien",
  "Chauffagiste",
  "Couvreur",
  "Vitrier",
  "Menuisier",
  "Serrurier",
  "Maçon",
  "Peintre",
  "Carreleur",
  "Paysagiste",
  "Restaurant",
  "Hôtel",
  "Coiffeur",
  "Dentiste",
  "Kinésithérapeute",
  "Vétérinaire",
  "Avocat",
  "Comptable",
  "Agence immobilière",
];

export const villes = [
  "Paris",
  "Lyon",
  "Marseille",
  "Toulouse",
  "Nice",
  "Bordeaux",
  "Lille",
  "Nantes",
  "Strasbourg",
  "Montpellier",
];

export const plans = [
  {
    id: "starter",
    name: "Starter",
    priceMonthly: 235,
    priceYearly: 449,
    description: "30 avis 100% authentiques. Parfait pour démarrer.",
    features: [
      "Google Business Profile",
      "Dashboard analytics en temps réel",
      "Account Manager dédié 24/7",
      "30 Avis 100% authentiques",
      "Profils vérifiés et réels",
      "Intégration CRM et outils métiers",
      "30% de suppression d'avis négatifs",
      "SEO intégré : mots-clés activité & localisation",
      "20% de validation garanti si fiche inférieure à 3 avis",
    ],
    cta: "Commander maintenant",
    popular: false,
  },
  {
    id: "pro",
    name: "Professionnel",
    priceMonthly: 299,
    priceYearly: 552,
    description: "60 avis 100% authentiques. Le plus populaire.",
    features: [
      "Google Business Profile",
      "Facebook",
      "Dashboard analytics en temps réel",
      "Account Manager dédié 24/7",
      "60 Avis 100% authentiques",
      "Profils vérifiés et réels",
      "Intégration CRM et outils métiers",
      "50% de remplacement après suppression",
      "SEO intégré : mots-clés activité & localisation",
      "20% de validation garanti si fiche inférieure à 3 avis",
      "40% de Guides Locaux avec profil noté supérieur à 4",
    ],
    cta: "Commander maintenant",
    popular: true,
  },
  {
    id: "entreprise",
    name: "Entreprise",
    priceMonthly: 499,
    priceYearly: 1123,
    description: "90 avis + 2 fiches incluses. Pour les réseaux.",
    features: [
      "Google Business Profile",
      "Trustpilot",
      "Pages Jaunes",
      "Facebook et autres plateformes",
      "2 fiches incluses : 30 avis + 60 avis",
      "Dashboard analytics en temps réel",
      "Account Manager dédié 24/7",
      "90 Avis 100% authentiques",
      "Profils vérifiés et réels",
      "Intégration CRM et outils métiers",
      "Jusqu'à 5 signalements par fiche (mobilisation 25+ comptes Gmail)",
      "Jusqu'à 70% des avis supprimés remplacés",
      "SEO intégré : mots-clés activité & localisation",
      "20% de validation garanti si fiche inférieure à 3 avis",
      "50%+ de Guides Locaux avec profil noté supérieur à 4",
    ],
    cta: "Commander maintenant",
    popular: false,
  },
];
